name: {{cookiecutter.repo_name}}
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
  - setuptools
  - wheel
  - click
  - sphinx
  - coverage
  - flake8
  - awscli  
  - python-dotenv>=0.5.1
  - python=3
